org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mekanism_version=1.20.1-10.4.16.80
jei_version=15.20.0.126
curios_version=5.3.2+1.20.1

mod_id=mekccupgrades
mod_name=Mekanism Config Card Upgrades
mod_license=GNU GPL-3.0
mod_version=1.4.8
mod_group_id=com.lhy.mekccupgrades
mod_authors=lhy
mod_description=Extends Mekanism's configuration card so it also copies and pastes machine upgrade data.
